# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPZgATUAJ6jtRtYnHtJ05-7-5nbc6xat
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import re

def parse_table(url='https://svspb.net/danmark/bjudzhet.php?l=chernogorija'):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
    response = requests.get(url, headers=headers)
    html = response.text

    # Ищем все строки в таблице и излекаем все содержимое. С помощью AI установили, как учитывать пропуски - добавлением re.DOTALL
    row_pattern = re.compile(r'<tr.*?>(.*?)</tr>', re.DOTALL)
    cell_pattern = re.compile(r'<td.*?>(.*?)</td>', re.DOTALL)

    rows = row_pattern.findall(html)

    data = []
    for row in rows[3:]:
        cells = cell_pattern.findall(row)
        if len(cells) == 4:
            year, income, expense, balance = cells
            data.append([year, income, expense, balance])

    df = pd.DataFrame(data, columns=['Год', 'Доходы', 'Расходы', 'Сальдо'])
    return df


df = parse_table()
print(df)

def fix(new_df: pd.DataFrame):

    final_dataframe = new_df.copy()

    numeric_columns = ['Сальдо']

    for col in numeric_columns:
        final_dataframe[col] = (
        final_dataframe[col]
            .str.replace(',', '.')
            .astype(float))

    return final_dataframe

final_dataframe = fix(parse_table())
print(final_dataframe)

def show_saldo(df):

    plt.figure(figsize=(14, 6))
    plt.plot(df['Год'], df['Сальдо'].astype(float))
    plt.title('Сальдо государственного бюджета Черногории по годам')
    plt.xlabel('Год')
    plt.ylabel('Сальдо (млрд. €)')
    plt.grid(True)

print(show_saldo(fix(parse_table())))